pos1-posmode       =ppp-static
pos1-frequency     =l1+2
pos1-soltype       =forward
pos1-elmask        =10
pos1-dynamics      =off
pos1-tidecorr      =on
pos1-ionoopt       =dual-freq
pos1-tropopt       =est-ztd
pos1-sateph        =brdc
pos1-posopt1       =on
pos1-posopt2       =on
pos1-posopt3       =on
pos1-posopt4       =on
pos1-posopt5       =off
pos1-posopt6       =off
pos1-navsys        =61
pos2-armode        =off
out-solformat      =xyz
out-outhead        =off
out-outopt         =off
out-outvel         =off
out-timesys        =gpst
out-timeform       =hms
out-timendec       =3
out-fieldsep       =
out-outsingle      =off
out-solstatic      =all
ant1-postype       =rinexhead
ant1-anttype       =*
ant1-antdele       =0
ant1-antdeln       =0
ant1-antdelu       =0
file-satantfile    =
file-rcvantfile    =
file-geoidfile     =
file-ionofile      =
file-dcbfile       =
file-eopfile       =
file-blqfile       =
file-fcbfile       =
file-biafile       =
file-tempdir       =
file-geexefile     =
file-solstatfile   =
file-tracefile     =
