#!/usr/bin/env python3
import os
import runpy
import sys


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    tool = os.path.join(root, "tools", "rtk_stats.py")
    os.environ["GNSS_CLI_NAME"] = os.path.basename(sys.argv[0])
    runpy.run_path(tool, run_name="__main__")


if __name__ == "__main__":
    main()
